### ISSUE TITLE
Will you release the code about implementation based on BM25

### ISSUE THREAD

**Issue by 0ddAstronaut** [pmc-patients/pmc-patients#1]
Thank you so much for your excellent work on this dataset collection! Will you consider releasing the code for implementing BM25? In this case, we can quickly reproduce the result.

**Comment by zhao-zy15** [comment]
Hi @0ddAstronaut , thank you a lot for your interest in our dataset!
We have released the code for reproducing all the baseline methods implemented in our paper at this repo:
https://github.com/zhao-zy15/PMC-Patients
The BM25 implementation is under the path code/downstream_task/baseline/PAR(or PPR)/BM25. We implement BM25 baseline with elasticsearch, so you have to first install that on your machine or deploy it on your server.
Please feel free to contact us if you have any further questions (through emails maybe if we haven't replied in time on Github). Good luck!

**Comment by 0ddAstronaut** [comment]
Thank you for the code repository! Looks very helpful!
